#structural parameter
baseline: 0.1

#Controller parameters
#inner loop
k_p_i: 3.2 #3.8
k_i_i: 0.05
k_d_i: 0.0
sati_i: 1.0
satd_i: 1.0
omegasat: 4.0
#outer loop
k_p_o: 3.7
k_i_o: 0.1
k_d_o: 0.0
sat_phi: 1.5 #~pi/2
sati_o: 1.0

#base speed
vref: 0.2


